const projects = [
  {
    id: 1,
    title: "Khidma DB",
    role: "Database Architecture",
    outcome: "63 procedures and 26 reporting views delivered",
    description:
      "Designed the database layer for a service marketplace platform, delivering 63 stored procedures and 26 SQL views to support workflows, reporting, and relational integrity.",
    image: "Khidma.png",
    imageDark: "Khidma.png",
    imageWidth: 432,
    imageHeight: 717,
    gitHubLink: "https://github.com/AhmedSaad-EGY/Khidma",
    liveDemoLink: "#",
    erdLink: "https://github.com/AhmedSaad-EGY/Khidma#database-schema",
    tags: ["SQL Server", "Stored Procedures", "Views"],
  },
  {
    id: 3,
    title: "AS Store",
    role: "Frontend SPA Development",
    outcome: "Dynamic catalog, cart, and client-side filtering workflows",
    description:
      "Developed an e-commerce SPA with Vue 3, including dynamic catalog browsing, cart interactions, and responsive client-side search and filtering workflows.",
    image: "AS_Store.png",
    imageDark: "AS_Store.png",
    imageWidth: 435,
    imageHeight: 724,
    gitHubLink: "https://github.com/AhmedSaad-EGY/AS_Store",
    liveDemoLink: "https://ahmedsaadstore.vercel.app/",
    tags: ["Vue.js 3", "Bootstrap 5"],
  },
  {
    id: 4,
    title: "Eng/Amr's Portfolio",
    role: "Client-Facing Website Delivery",
    outcome: "Responsive UI polished for desktop and mobile browsing",
    description:
      "Delivered a professional portfolio website with responsive layouts, polished UI presentation, and smooth browsing across desktop and mobile screens.",
    image: "amr-light.png",
    imageDark: "amr-dark.png",
    imageWidth: 1280,
    imageHeight: 720,
    gitHubLink: "https://github.com/AhmedSaad-EGY/Eng.Amr-Adel-Portfolio",
    liveDemoLink: "https://amradel.vercel.app/",
    tags: ["HTML", "CSS", "JavaScript", "Bootstrap 5"],
  },
  {
    id: 2,
    title: "Landing Page",
    role: "Performance-Focused Frontend",
    outcome: "Clean UX structure with strong Lighthouse performance",
    description:
      "Built a responsive landing page with semantic HTML, structured CSS, and a performance-focused frontend approach aimed at clean UX and strong Lighthouse results.",
    image: "LandingPage.png",
    imageDark: "LandingPage.png",
    imageWidth: 435,
    imageHeight: 715,
    gitHubLink: "https://github.com/AhmedSaad-EGY/LandingPage1",
    liveDemoLink: "https://architects-br.vercel.app/",
    tags: ["HTML", "CSS", "Bootstrap 5"],
  },
];

window.projects = projects;
