const projects = [
  {
    id: 5,
    title: "Saiyad",
    role: "Full-Stack .NET Development",
    outcome:
      "110+ APIs, 5 roles, wallet logic, and auction workflows delivered",
    description:
      "Built a full-stack marketplace and auction platform for the fishing community using ASP.NET Core, SQL Server, EF Core, Clean Architecture, JWT authentication, role-based authorization, SQL Server transactions, and a Vanilla JavaScript ES6+ SPA frontend. The platform includes product, cart, checkout, order, auction, wallet, admin, authentication, and role-based workflows.",
    image: "Images/Saiyad.png",
    imageDark: "Images/Saiyad.png",
    imageWebp: "Images/Saiyad.webp",
    imageDarkWebp: "Images/Saiyad.webp",
    imageWidth: 1280,
    imageHeight: 720,
    badges: ["Main Project", "Full-Stack", "Live", "Clean Architecture"],
    proofPoints: [
      "UI and backend repositories available",
      "110+ RESTful API endpoints",
      "5 role-based workflows",
      "SQL Server transaction-backed auctions",
    ],
    links: [
      {
        label: "UI GitHub",
        href: "https://github.com/AhmedSaad-EGY/Saiyad_UI",
        icon: "fa-brands fa-github",
      },
      {
        label: "Backend GitHub",
        href: "https://github.com/AhmedSaad-EGY/Saiyad",
        icon: "fa-brands fa-github",
      },
      {
        label: "Live Demo",
        href: "https://saiyad-eg.vercel.app",
        icon: "fa-solid fa-arrow-up-right-from-square",
      },
    ],
    tags: [
      "ASP.NET Core",
      ".NET 10",
      "SQL Server",
      "EF Core",
      "Clean Architecture",
      "JWT",
      "Vanilla JavaScript",
      "Bootstrap 5",
    ],
  },
  {
    id: 1,
    title: "Khidma DB",
    role: "Database Architecture",
    outcome: "63 procedures and 26 reporting views delivered",
    description:
      "Designed the database layer for a service marketplace platform, delivering 63 stored procedures and 26 SQL views to support workflows, reporting, and relational integrity.",
    image: "Images/Khidma.png",
    imageDark: "Images/Khidma.png",
    imageWebp: "Images/Khidma.webp",
    imageDarkWebp: "Images/Khidma.webp",
    imageWidth: 432,
    imageHeight: 717,
    badges: ["Backend", "Database"],
    gitHubLink: "https://github.com/AhmedSaad-EGY/Khidma",
    liveDemoLink: "#",
    erdLink: "https://github.com/AhmedSaad-EGY/Khidma#database-schema",
    tags: ["SQL Server", "Stored Procedures", "Views"],
  },
  {
    id: 3,
    title: "AS Store",
    role: "Frontend SPA Development",
    outcome: "Dynamic catalog, cart, and client-side filtering workflows",
    description:
      "Developed an e-commerce SPA with Vue 3, including dynamic catalog browsing, cart interactions, and responsive client-side search and filtering workflows.",
    image: "Images/AS_Store.png",
    imageDark: "Images/AS_Store.png",
    imageWebp: "Images/AS_Store.webp",
    imageDarkWebp: "Images/AS_Store.webp",
    imageWidth: 435,
    imageHeight: 724,
    badges: ["Frontend", "SPA", "Live"],
    gitHubLink: "https://github.com/AhmedSaad-EGY/AS_Store",
    liveDemoLink: "https://ahmedsaadstore.vercel.app/",
    tags: ["Vue.js 3", "Bootstrap 5"],
  },
  {
    id: 4,
    title: "Eng/Amr's Portfolio",
    role: "Client-Facing Website Delivery",
    outcome: "Responsive UI polished for desktop and mobile browsing",
    description:
      "Delivered a professional portfolio website with responsive layouts, polished UI presentation, and smooth browsing across desktop and mobile screens.",
    image: "Images/amr-light.png",
    imageDark: "Images/amr-dark.png",
    imageWebp: "Images/amr-light.webp",
    imageDarkWebp: "Images/amr-dark.webp",
    imageWidth: 1280,
    imageHeight: 720,
    badges: ["Frontend", "Client Work", "Live"],
    gitHubLink: "https://github.com/AhmedSaad-EGY/Eng.Amr-Adel-Portfolio",
    liveDemoLink: "https://amradel.vercel.app/",
    tags: ["HTML", "CSS", "JavaScript", "Bootstrap 5"],
  },
  {
    id: 2,
    title: "Landing Page",
    role: "Performance-Focused Frontend",
    outcome: "Clean UX structure with strong Lighthouse performance",
    description:
      "Built a responsive landing page with semantic HTML, structured CSS, and a performance-focused frontend approach aimed at clean UX and strong Lighthouse results.",
    image: "Images/LandingPage.png",
    imageDark: "Images/LandingPage.png",
    imageWebp: "Images/LandingPage.webp",
    imageDarkWebp: "Images/LandingPage.webp",
    imageWidth: 435,
    imageHeight: 715,
    badges: ["Frontend", "Landing Page", "Live"],
    gitHubLink: "https://github.com/AhmedSaad-EGY/LandingPage1",
    liveDemoLink: "https://architects-br.vercel.app/",
    tags: ["HTML", "CSS", "Bootstrap 5"],
  },
];

window.projects = projects;
